import SiteNavbar from "@/components/SiteNavbar";
import "./globals.css";
import SiteFooter from "@/components/SiteFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SiteNavbar></SiteNavbar>
        {children}
        <SiteFooter></SiteFooter>
      </body>
    </html>
  );
}
